### ISSUE TITLE
Some Links for Test Code are Failure

### ISSUE THREAD

**Issue by abby50066** [JihyongOh/FISR#10]
As title, 
Some Links for Test Code are Failure.

1. Step 3 in Test code, for downloading pre-train weights:
Download the pre-trained weights from this link and then unzip it to place in <source_path>/checkpoint_dir/FISRnet_exp1.

2.  Description in Test code: 
How to make flow and warped files by using PWC-Net: you can download all the related tensorflow files from this link including weights, and then modify the folder name ‘tfoptflow’ as ‘FISR_tfoptflow’.

Could you please share these two links for running test code.

**Comment by JihyongOh** [comment]
Hello, @abby50066 !
Thank you for your interest.
1. I don't know the reason why that link is changed, so I have modified it.
2. Since the code for PWC-Net was brought from that link and then modified, you have to follow these instructions: 
- "How to make flow and warped files by using PWC-Net: you can download all the related tensorflow files from this link including weights, and then modify the folder name ‘tfoptflow’ as ‘FISR_tfoptflow’. Insert(download) all our modified versions for ‘test’ and 'FISR_for_video' phase placed in the ‘FISR_tfoptflow’ folder. For 'test', you can make .flo flow file by using ‘FISR_pwcnet_predict_from_img_test.py’ and then get .mat warped file by using ‘FISR_warp_mat_with_flo.py’. For 'FISR_for_video', you can sequentially get a '.flo' file and a '.mat' warped file for FISR testing in 'scene1'(our example), according to YUV format files in 'scene1'(our example) folder."

Thank you:)

**Comment by abby50066** [comment]
Thank you~
